#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="ls -d */ | sed 's/\//,/g' | xargs | sed -e 's/ //g' -e 's/,$//g'"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

$DOTFILES/dependencies
STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
