#!/usr/bin/env bash

yay -Syu

# Core
yay -S make cmake gcc clang base base-devel git moreutils unzip python-pip

# Utilities

yay -S ripgrep bat tmux zsh stow xclip xsel tree luarocks

git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma-continuum/zinit/master/doc/install.sh)"

sudo pip3 install -U Commitizen

# Languages

yay -S go rust python

# Probably shall query this through a querier
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

# Neovim

mkdir -p "$HOME/git-stuff"

pushd "$HOME/git-stuff" || return

git clone https://github.com/neovim/neovim

pushd neovim || return

make CMAKE_BUILD_TYPE=Release
sudo make install

popd || return ; popd || return

yay -S eslint_d stylua shfmt prettierd omnisharp-roslyn lua-language-server bash-language-server typescript-language-server vscode-html-languageserver vscode-css-languageserver pyright rust-analyzer ruby-solargraph luacheck

# NvChad
git clone https://github.com/NvChad/NvChad ~/.config/nvim
