#!/usr/bin/env zsh

pushd $DOTFILES

echo $DOTFILES
for folder in $(sed 's/,/ /g'<<<$STOW_FOLDERS)
do
    stow --restow $folder

    # If the folder already exists --restow will fail.
    # In that case, we need to stow with the --adopt flag which will overwrite the existing files.
    if [ $? -ne 0 ]; then
        stow --adopt $folder
    fi
done

post-install

popd
