#!/usr/bin/env zsh

source ~/.zshrc

nvm install node

npm install --global yarn

pip install --user --upgraded pynvim

npm install -g neovim

nvim +'hi NormalFloat guibg=#1e222a' +PackerSync

npm install -g fx
