#!/usr/bin/env bash

REPLACE_ID=5555  # Arbitrary ID for our notifications

active_sink=$(pactl list short sinks | grep RUNNING | awk '{print $1}')

if [[ -z "$active_sink" ]]; then
    notify-send -u normal -r $REPLACE_ID "Error" "No active sink found"
    exit 1
fi

if [ "$#" -ne 1 ]; then
    notify-send -u normal -r $REPLACE_ID "Error" "Invalid arguments. Please use 'up' or 'down'."
    exit 1
fi

if [ "$1" = "up" ]; then
    pactl set-sink-volume "$active_sink" +5%
elif [ "$1" = "down" ]; then
    pactl set-sink-volume "$active_sink" -5%
else
    notify-send -u normal -r $REPLACE_ID "Error" "Invalid argument. Please use 'up' or 'down'."
    exit 1
fi

# Get the new volume
new_vol=$(pactl list sinks | grep '^[[:space:]]Volume:' | \
head -n $(( active_sink )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

# Notify the new volume
notify-send -u normal -r $REPLACE_ID "Volume" "New volume is $new_vol%"

exit 0
