version: '3.7'

services:
  server:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
        GIT_USER_NAME: Daniel Boll
        GIT_USER_EMAIL: danielboll.academico@gmail.com
    environment:
      UID:
      GID:
